version: "3"
services:

  api:
    build:
      context: ./bitfinex_orderbook
      dockerfile: Dockerfile

    restart: on-failure

  youtube:
    build:
      context: ./youtube
      dockerfile: Dockerfile

    restart: on-failure